# Environment Settings
namespace: default
environment: default
hostname: fastapi.localhost
modelName: "mambaout_femto.in1k"

# Config Versions
configVersions:
  webServer: v1
  modelServer: v1
  redis: v1

# UI Server Next JS
uiServer:
  image:
    repository: 306093656765.dkr.ecr.ap-south-1.amazonaws.com/a15/ui-server
    tag: latest

# Web Server
webServer:
  image:
    repository: 306093656765.dkr.ecr.ap-south-1.amazonaws.com/a15/web-server
    tag: latest

# Model Server
modelServer:
  image:
    repository: 306093656765.dkr.ecr.ap-south-1.amazonaws.com/a15/model-server
    tag: latest
  resources:
      requests:
          cpu: "600m"    # Average CPU usage is around 700m
          memory: "600Mi" # Average memory usage is around 600Mi
      limits:
          cpu: "1000m"   # Set limit to 1 CPU core
          memory: "800Mi" # Set memory limit to 800Mi

# Redis
redis:
  image:
    repository: redis
    tag: 7.4.1
  resources:
    memory: "200Mi"
    cpu: "200m"
  password: "default-password"